Backend: Vivado
ClockPeriod: 5
HLSConfig:
  Model:
    BramFactor: 1000000000
    Precision: ap_fixed<8,2>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_2/hls4ml_prj/keras_model.h5'
OutputDir: model_2/hls4ml_prj
OutputPredictions: null
Part: xczu49dr-2ffvf1760
ProjectName: myproject
Stamp: ac95c1ED
